### ISSUE TITLE
Application icon hard to read / lens should have a "real" logo

### ISSUE THREAD

**Issue by headcr4sh** [lensapp/lens#142]
**What would you like to be added**:
I think, the icon that currently ships with Lens is not suited to represent the application.
- it is barely readable / understandable (especially in small sizes such as 16x16 or even 32x32)
- It does not contain any pictogram and basically contains only the text "Lens by Kontena"
- Kontena has ceased operations :-( -- even though I do believe, that it's name should be mentioned somehow, I have the feeling that the icon might be the wrong place

**Why is this needed**:
- Improve UX
- Establish a strong (app) brand

**Comment by headcr4sh** [comment]
Here is a very first proposal:

![lens-logo-proposal](https://user-images.githubusercontent.com/196779/77207598-14b50f80-6afa-11ea-83a1-9411a5a831e2.png)

A shutter lens that zooms onto the Kubernetes logo. Well,......

**Comment by miskun** [comment]
Yes, I agree. We need to change the icon and have proper logo for the app. 

Same icon/logo should be used throughout the app and any related services like https://k8slens.dev website, https://twitter.com/k8slens Twitter account, this GitHub account etc.

**Comment by miskun** [comment]
This shutter concept with K8S logo is very nice. Some ideas / feedback:
* I'd probably change the shutter shape from "hexagon" to "heptagon" to match kubernetes logo shape. And have K8S logo in the center.
* The choice of colors is important too; I'd change the color of kubernetes logo to something that is more bright. To cut some corners, we could simply use #3d90ce in memory of Kontena (that was Kontena brand color). The added benefit in here is that we don't need to change color throughout the app UI itself since kontena primary color is already used in there. The color of shutter itself would work well in gray.
* We could try to use some subtle gradients in RGB version.

**Comment by jakolehm** [comment]
Lens 3.1 will have a new logo that is used already on the website. I think this issue is still valid, we need a better logo at some point.

**Comment by jakolehm** [comment]
Website just got a new "shutter" like logo, we should also change app logo. https://github.com/lensapp/lensapp.github.io/pull/2
