### ISSUE TITLE
Copy Logs from tabs on windows

### ISSUE THREAD

**Issue by josepowera** [lensapp/lens#1810]
**Describe the bug**
When Copy pasting logs on Windows line endings get broken

**To Reproduce**
On previous version Logs from Pods containers were shown in separate window. You could copy-paste to notepad and linebreaks would be as in Lens.

On last version Logs from Pods containers are shown in Tabs. Now if you copy-paste to notepad (running on windows) line breaks have changed... If you copy paste multiple lines in last version, all lines will be word-wrapped -  in SAME line.

**Expected behavior**
On windows probably you have to change line-endings

**Environment (please complete the following information):**
- Lens Version:  4.0.3
- OS: Windows 10

**Comment by moreinhardt** [comment]
I can confirm the same behaviour on Linux since a recent update. Reduces the usability of the log access functionality significantly :disappointed: 

Lens: 4.0.3
Electron: 9.3.5
Chrome: 83.0.4103.122
Node: 12.14.1

Ubuntu 20.04

**Comment by aleksfront** [comment]
@josepowera @moreinhardt Thanks for reporting this! The issue is currently fixed, however there's option to download logs with all line breaks preserved. Just use the according `Save` button on the toolbar
![download logs](https://user-images.githubusercontent.com/9607060/102995777-cfaf8500-4532-11eb-8ade-14e2dc5270a2.png)
