### ISSUE TITLE
Close when the close button is clicked, don't go in background.

### ISSUE THREAD

**Issue by atrauzzi** [lensapp/lens#1906]
**Describe the bug**
When I close lens, it doesn't close.

**To Reproduce**
Try closing lens.

**Expected behavior**
For lens to not be running anymore.

**Environment (please complete the following information):**
- Lens Version: 4.0.6
- OS: Ubuntu 20.10
- Installation method : Snap
---

I don't have lens running on startup.

The default behaviour shouldn't be for lens to background when closed, that's a misuse of the default close behaviour.  This should be opt-in.  I see no options in preferences to disable this behaviour.

**Comment by ruckc** [comment]
concur... this also breaks auto-updates on exit, as it sits in background instead of exiting and subsequently updating.

**Comment by Nokel81** [comment]
The auto update issue has been fixed by #1941.

**Comment by atrauzzi** [comment]
Please ensure that the default behaviour is to exit completely when the window is closed. People can then enable functionality that contradicts all known OS norms with an option.

**Comment by dparker18** [comment]
> Please ensure that the default behaviour is to exit completely when the window is closed. People can then enable functionality that contradicts all known OS norms with an option.

Agreed. Please bring back the principle of least surprise

**Comment by MindWithCake** [comment]
> The default behaviour shouldn't be for lens to background when closed, that's a misuse of the default close behaviour. This should be opt-in. I see no options in preferences to disable this behaviour.

I totally agree. Staying in background can be a sensitive choice for chat apps, cloud drives and other "demon like" application, but it's seldomly useful for an IDE, and even in those legitimate use case I've always been given an option to actually quit instead of reducing to tray.

As a side note, even the "quit app" keyboard shortcut <kbd>alt</kbd> + <kbd>f4</kbd> has the same behaviour of reducing to tray.

The current intended way to quit lens on linux is to click the close button, right click the tray icon and click the "quit" menu option, which is quite cumbersome, I really wish for a "quit on quit" option to be implemented...

**Environment**:
- OpenLens Version 6.5.2
- OS: Arch Linux, kernel 6.5.4-arch2-1
- Desktop: GNOME Shell 44.5 on Wayland
- Installation method: [AUR package](https://aur.archlinux.org/packages/openlens-bin)

**Comment by shanehickeylk** [comment]
This is still an issue. Why has it been closed?
