### ISSUE TITLE
Logs doesn't preserve log indentation

### ISSUE THREAD

**Issue by aleksfront** [lensapp/lens#2240]
Log view shoud respect indentation spaces for log lines.

Problem: Lens log view on left, and terminal on right.

<img width="1272" alt="Screen Shot 2021-02-26 at 1 47 06 PM" src="https://user-images.githubusercontent.com/9607060/109297432-095a8000-7843-11eb-951b-86a34e675bf4.png">

**Comment by seanhamlin** [comment]
Another example is the Nuxt logo (`logs -f` on the left, and `lens` on the right):

![image](https://user-images.githubusercontent.com/10605846/109445156-d8c55100-7aa3-11eb-93a7-39e00d1e9d40.png)

This confused me for a bit when following a build.

**Comment by LaysDragon** [comment]
Another example is go framework echo logo and the formatted text table.
![image](https://user-images.githubusercontent.com/10185394/111104773-661ca100-858c-11eb-94b6-49e7c02c06eb.png)

**Comment by avatarneil** [comment]
I think that this is related to #2412, and due to the changes introduced in #1938. Without the `pre` white-space styling for the `.LogRow` class, I'm pretty sure the multiple spaces used for indentation are being collapsed into a single space in the `<span>`. Because many logging frameworks will use spaces for indentation (very common example is emitting JSON logs), this poses a bit of an issue! 

I attempted to switch the white-space styling back to `pre` on my machine and indentation was properly preserved (woot!); however, I couldn't reproduce the bug reported in #1706 after reverting the change made in #1938, so I'm not sure if switching back to `pre` white-space styling is a viable solution (the bug in #1706 may return if the change is reverted).

**Comment by aleksfront** [comment]
Fixed in #2655
<img width="627" alt="log table" src="https://user-images.githubusercontent.com/9607060/159434221-40cc70cd-5791-40c3-a983-a1b39b2ec322.png">
