### ISSUE TITLE
admissionregistration objects - mutating and validating webhook configurations

### ISSUE THREAD

**Issue by brettcave** [lensapp/lens#2322]
Kubernetes offers extensible admission controllers - https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/

These are available in kubectl, e.g. `kubectl get mutatingwebhookconfigurations` (or `validatingwebhookconfigurations`). 

**Why is this needed**: these  are objects that may be deployed in a namespace. Given that they form part of a deployment / is a configured resource, it would be great if LENS could manage it, instead of needing to revert to other tools.

Specific use-case where this was a problem: trying to remove all resources and delete a namespace, this was the only resource from a broken deployment that i couldn't clean up with LENS.

**Environment you are Lens application on:**

- Kubernetes distribution: EKS 1.19
- Desktop OS: Windows 10 (latest)
- LENS - latest update - 4.1.4

**Comment by doug-shontz** [comment]
If you deploy ElasticSearch on K8s they use a validatingwebhook as well.  Plus they have a bad habit of having base configurations that need updating in order to deal with hosted K8s solutions (such as Digital Ocean).  Not that it's a problem to change it with kubectl, but, at this point, Lens is so good that I kind of smirk to myself when I have to use kubectl!

:)

**Comment by waldner** [comment]
What's the status of this? Are there impediments to adding those two resources?

**Comment by schmurfy** [comment]
any news ?

**Comment by alex-bes** [comment]
+1
