### ISSUE TITLE
Make cluster presence detection an optional feature

### ISSUE THREAD

**Issue by mverleun** [lensapp/lens#2326]
**What would you like to be added**:

I would like to add the ability to flag certain clusters as persistent, meaning that Lens should not report these clusters as being invalid when they can not be reached. 

**Why is this needed**:

I do support many clusters. Some are private cloud, others are in public cloud. Some require a VPN connection, others a proxy to be reachable.

Currently Lens is checking if these clusters are reachable which they are not always. If a cluster can not be reached a warning pops up with the recommendation to fix the .kube/config file.

**Environment you are Lens application on:**

- Kubernetes distribution: AKS, Rancher, Minikube, KinD, K3S
- Desktop OS: macOS 11.2.3 with Lens 4.1.4

**Comment by jim-docker** [comment]
Hi, what do you mean by "cannot be reached"? If Lens cannot connect to a cluster it will not report the cluster as invalid. In Lens 4.1.4 we added some kubeconfig validation, which checks if the expected fields are present (context, cluster, user, etc). Is this what is happening? Does your context get removed from the kubeconfig (by something other than Lens) when it becomes unreachable?

**Comment by mverleun** [comment]
That is exactly what is happening. I was not aware of the details. But yes, the kubeconfig file is modified automatically. 
But these clusters often are added again as well so it would be nice if they stay in the group in which they were placed.

**Comment by jim-docker** [comment]
Ok, I think this is not what we expected in terms of cluster workflow and how clusters become unreachable. Are you essentially deleting a cluster and creating a new one with the same name? Can you make it so that the cluster is not removed from the kubeconfig?

FYI if you cancel the invalid kubeconfig notification, the cluster won't be removed from Lens. However, to see the cluster again in Lens, once the cluster is restored in the kubeconfig, you must restart Lens. The cluster will then appear again in the UI. I know this is not the best UX, we could possibly support it on reload as well.

**Comment by mverleun** [comment]
I understand that it is not a common way of working. But at the moment I do have 26 clusters in my kubeconfig.
And I do love Lens to work with them, it's the best I've seen so far.

I guess I'll have to restart Lens every now and then when the kubeconfig changes, not really a big deal, but it would have been nice if I didn't get the notification that a cluster has been removed.
Maybe that's a better request to submit. To be able to silently accept that clusters have been removed...

Thanks for your time on this issue.

**Comment by Nokel81** [comment]
This is no longer checked for and the clusters will now reappear if they are readded.
