### ISSUE TITLE
Blank dashboard after sleep

### ISSUE THREAD

**Issue by jim-docker** [lensapp/lens#2434]
Leaving Lens running/open when computer sleeps results in blank dashboard for the cluster that was connected, upon awakening the computer.

https://user-images.githubusercontent.com/40840436/113300835-5a3f1780-92cc-11eb-9c31-02be3934c960.mov

Dashboard is recovered for the the cluster by disconnecting it and then reconnecting it (Or restarting Lens)

Lens 4.2.0, observed on Windows 10

**Comment by jakolehm** [comment]
@jim-docker still an issue?

**Comment by jim-docker** [comment]
Yes

![Screen Shot 2021-05-27 at 9 31 23 AM](https://user-images.githubusercontent.com/40840436/119835027-775c2500-bece-11eb-8822-b43fd28a5c2b.png)

**Comment by dominch** [comment]
Instead of opening new ticket I found this one, yes - this is still an issue. It occurs on networks where some time is needed after sleep/resume to reconnect to Internet, like vpn or some group policy with proxy server. You may easily reproduce that just by turning off wifi/ethernet and sleep/resume for few minutes (i'm not sure how long is cache). 

On dev console there are plenty of errors: 

![image](https://user-images.githubusercontent.com/10815109/137290227-454b9845-4b9a-4621-85a5-a469cac247d7.png)

I'm on newest lens version: 

![image](https://user-images.githubusercontent.com/10815109/137290476-a5f7af85-619f-40d7-a171-a0262bdabe8f.png)

Is there any way I can reload broken cluster? I can't do anything with that except to restart interface (not tray)
Interestingly when I connect to another cluster - it's ok. Going back to broken one - still blank.

**Comment by jim-docker** [comment]
@dominch for me just disconnecting the cluster (right click on the icon, pick Disconnect) and reconnecting works.

**Comment by dominch** [comment]
@jim-docker I just resumed my pc and like always hit that issue, Your solution works :) thanks, this is always better than restart :) 

I left lens maximized yesterday and today I saw how it behaves on resume. It display some connection/proxy errors (I don't use any proxy) and after few seconds it blanks connected clusters. On console some new errors: 
![image](https://user-images.githubusercontent.com/10815109/137443543-742fa30c-fc30-4398-9905-0d5626019c9e.png)
