### ISSUE TITLE
Add a view of  kind: IngressClass 

### ISSUE THREAD

**Issue by RotemBirman** [lensapp/lens#2576]
**What would you like to be added**:
Add a visibility for kind: IngressClass

**Why is this needed**:
Right now we have no UI representation of kind: IngressClass

**Environment you are Lens application on:**

- Kubernetes distribution: EKS 1.18 | EKS 1.19
- Desktop OS: Ubuntu 20.04

**API DOCS:**

- https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#ingressclass-v1-networking-k8s-io
- https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class

**Comment by Nokel81** [comment]
Further reading: https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class

**Comment by systemmonkey42** [comment]
Please add a check-box or button to toggle 'is-default-class' easily.

**Comment by gigi206** [comment]
:+1: for this feature

**Comment by viceice** [comment]
It was beta in v1.18+ (`networking.k8s.io/v1beta1/IngressClass`) and become stable since v1.19+ (`networking.k8s.io/v1/IngressClass`).

Beta version (`networking.k8s.io/v1beta1/IngressClass`) was removed in v1.22[^1].

[^1]: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingressclass-v122
