### ISSUE TITLE
Menu displayed for a connected cluster in the catalog view is off the page

### ISSUE THREAD

**Issue by stevejr** [lensapp/lens#2625]
**Describe the bug**
When you click on the `...` icon next to a connected cluster in the catalog view the menu renders off of the visible page.

**To Reproduce**
1. Go to catalog screen
2. Connect to a cluster and navigate back to the catalog screen
2. Click on `...` icon next to the connected cluster and the menu is displayed but is off of the screen.

**Expected behavior**

**Screenshots**

![Screenshot 2021-04-26 at 10 13 18](https://user-images.githubusercontent.com/14779471/116082300-28cf2700-a693-11eb-9ced-c2be721b53d6.png)

**Environment (please complete the following information):**
- Lens Version: 5.0.0-alpha.2
- OS: [e.g. OSX] OSX
- Installation method (e.g. snap or AppImage in Linux):

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by Nokel81** [comment]
The root cause of this problem is our design of how actions are completed. They are emitted and asynchronously responded to by pushing items back to the source (by the context passed in). This means that when the menu first opens and tries to figure out where to place itself it detects (correctly) that it is `Xpx` wide. However, before the user notices that it is open the asynchronous events have happened and the menu rerenders with now wider views.

@jakolehm FYI ^^^

---

I have come up with a minimal fix, but it would be nice to fix the underlying issue here properly (not opening the menu before the contents is ready). But that would require a complete rework of the catalog entity API.
