### ISSUE TITLE
Exception Handling for Protocol Handler

### ISSUE THREAD

**Issue by leenamba** [lensapp/lens#2747]
**What would you like to be added**:
When a Lens URL is not correct have a way to hand the exceptions

**Why is this needed**:
Currently Lens comes to the foreground but nothing happens. The user could be confused

**Comment by Nokel81** [comment]
@leenamba What sort of handling do you want? Like do you mean if an extension isn't installed show a notification? Or if there isn't a handler do some action?

I removed that sort of functionality from my initial implementation because it is non-trivial to solve:
- Where should the "missing route" handler be defined?
- Should the "missing route" handler run on both `main` and `renderer`?
- Should it run on one side (ie in `main`) if there is a handler on the other side (ie in `renderer`)?

**Comment by leenamba** [comment]
Agreed this is non-trivial. So until there is a more robust framework for handling this I propose a simple generic catch-all notification like:

`Sorry there was a problem with the Lens URL. Please check to see if there is an error in the URL or try upgrading to the latest version of Lens and/or extensions.`

**Comment by Nokel81** [comment]
@leenamba I disagree that a notification is a "simple catch-all". But I assume that your answers to my questions are:

- renderer
- no
- no

**Comment by Nokel81** [comment]
Currently targeting this for 5.0.0. Will create a backport PR once it is merged.
