### ISSUE TITLE
Javascript error in the main process

### ISSUE THREAD

**Issue by galalmounir** [lensapp/lens#3272]
**Describe the bug**
With a pod selected, a random popup will appear with an uncaught exception

**Screenshots**
![image](https://user-images.githubusercontent.com/2583382/124501406-7a7ce780-dd8f-11eb-801c-225b4dc4bf00.png)

**Environment:**
- Lens Version: 5.0.1+20210705.1
- OS: MacOS

**Comment by Nokel81** [comment]
Do you have write permissions for `~/.kube`?

**Comment by galalmounir** [comment]
Yes I do. This only started happening after the upgrade to v5

**Comment by Nokel81** [comment]
Okay thanks. I am trying to come up with a way to reproduce this issue on my machine. Because we don't try and read `config.lock` anywhere in our codebase I think it might be related to `kubectl` but I don't know enough about its internals yet.

**Comment by Nokel81** [comment]
Were you doing something in particular when this popup happened? For instance were you opening a local terminal instance?

**Comment by galalmounir** [comment]
I don't remember doing anything on the side. I'll try to repro again, but it keeps happening randomly.
Could it be related network connection/disconnection?

**Comment by Nokel81** [comment]
I have done some more reading and it could just be a race condition between two instances of `kubectl` running against the same config file.

**Comment by galalmounir** [comment]
Happened again this morning, this time my laptop was in sleep mode. Once I logged in, I found the same pop-up message.
After clicking `Ok` another message appeared:
![image](https://user-images.githubusercontent.com/2583382/125076769-502c7200-e08e-11eb-8987-5bbd74a40f75.png)

**Comment by Nokel81** [comment]
That might be related to kube sync thanks for the report.

**Comment by gdelbergue** [comment]
Having the same issue. It happens when I keep my computer running for night. Suddenly, fan speed increases, lens CPU usage is ~ 97% and there is a lock error.

![Screenshot 2021-07-14 at 11 01 49](https://user-images.githubusercontent.com/4040959/125597899-a105f946-f8e4-4fbe-a817-624712806a93.png)
<img width="980" alt="Screenshot 2021-07-14 at 11 19 14" src="https://user-images.githubusercontent.com/4040959/125597912-c79d2ca4-c690-439e-b5f2-49dc19567f21.png">

A click on "Ok" results then in this error:

![Screenshot 2021-07-14 at 11 23 24](https://user-images.githubusercontent.com/4040959/125598001-2b430ef5-beed-4a2f-b0ba-a419263bafe2.png)

Finally, CPU usage decreases and it starts again few seconds later.

![Screenshot 2021-07-14 at 11 24 11](https://user-images.githubusercontent.com/4040959/125598112-6f1376b5-432d-4298-aac8-aeca67fd7e84.png)

**Comment by Nokel81** [comment]
Sigh... JS's lack of event based tracing can sometimes be very annoying... 

I have narrowed this to not being part of kube-sync because we do catch and log errors there.

**Comment by Nokel81** [comment]
Does this still happen?

**Comment by Nokel81** [comment]
I think that #3452 fixes this as we no longer try to read .lock files.
