### ISSUE TITLE
Helm new version available is not correct

### ISSUE THREAD

**Issue by winggundamth** [lensapp/lens#361]
**Describe the bug**
I'm using cert-manager chart 0.15.0 that is today latest version. But Lens showing that there is new version available that's is v0.6.7 (I think it's from old deprecated chart). See screenshot below

**To Reproduce**
1. Install cert-manager chart with version 0.15.0
2. Click on 'Apps > Releases'
3. You will see there is new version available

**Expected behavior**
There should not showing new version available

**Screenshots**
![Selection_222](https://user-images.githubusercontent.com/4833238/81504120-b5ad9300-9311-11ea-9ce7-e9336de4cddb.png)

**Environment (please complete the following information):**
- Lens Version: 3.4.0
- Linux: Ubuntu 20.04 LTS
- Installation method: snap

**Comment by Nuru** [comment]
The current version of the [deprecated chart](https://github.com/helm/charts/blob/35f2a3e7cc78052928e0a38691916c133e5cf2f5/stable/cert-manager/Chart.yaml) is v0.6.7, but it deploys app version v0.6.2. 

1. The "version" field should track versions of the app, not the chart. Updates to the app bring new features and/or bug and security fixes. Updates to the chart are usually not interesting.
2. It would, of course, be better to use the official chart. However, I do not know of any standard way of finding out where the installed chart came from. @winggundamth What happens if you add the jetstack repo to your set of repos in Lens -> Preferences? 
3. On my instance of Lens, I do not get a message about cert-manager, I just get spinning dots. I do not know why.
4. Many charts allow you to override the app version. It would be helpful if the display also included the actual app version or Docker image tag of the deployed app. Could be tricky for charts that deploy multiple images/containers.

**Comment by winggundamth** [comment]
@Nuru I added jetstack repo as you said but it still showing new version available. I think both chart and app version is 1.15.0 as helm list below

```
$ helm list --namespace cert-manager 
NAME        	NAMESPACE   	REVISION	UPDATED                                	STATUS  	CHART               	APP VERSION
cert-manager	cert-manager	2       	2020-05-08 12:47:03.256144979 +0000 UTC	deployed	cert-manager-v0.15.0	v0.15.0
```

![Selection_223](https://user-images.githubusercontent.com/4833238/81507734-7c811d00-9329-11ea-8a53-b915be2fe435.png)

![Selection_224](https://user-images.githubusercontent.com/4833238/81507778-c7029980-9329-11ea-88f2-987dcbd93e2a.png)

![Selection_225](https://user-images.githubusercontent.com/4833238/81507817-003b0980-932a-11ea-84a9-54b870a3e409.png)

**Comment by wjrogers** [comment]
It also shows incorrect "new version" notifications when charts have been installed from repositories other than the official "stable" repository (which is deprecated).

**Comment by Nuru** [comment]
> It also shows incorrect "new version" notifications when charts have been installed from repositories other than the official "stable" repository (which is deprecated).

I think there are enough problems with this feature from a design/concept perspective that it should be considered experimental, made optional, and disabled by default. The fact that the official helm stable repository is itself [deprecated](https://github.com/helm/charts#status-of-the-project) is the last straw for me.

**Comment by jakolehm** [comment]
There is no way Lens can know which repo was used to deploy a release. We probably need to disable "new version" notification for now.
