### ISSUE TITLE
Logs view timestamps cause misaligned output

### ISSUE THREAD

**Issue by gbritton** [lensapp/lens#380]
**Describe the bug**
The log view for a pod, etc. shows each line prefixed by an rfc3339 timestamp, but the subsecond field isn't being rendered as a fixed 9-digit nanoseconds, so when the last digit is a 0, it's dropped and log output ends up not aligned.

**To Reproduce**
1. View logs on a pod
2. Repeat a few times until one of the nanosecond fields ends in 0's.

**Expected behavior**
Logging timestamps should always be fixed width.  The nanosecond field should always be 9 digits wide, padding with 0's on both sides as necessary.

**Screenshots**
```
2020-05-17T14:10:06.421372144Z apiVersion: externaldns.k8s.io/v1alpha1
2020-05-17T14:10:06.42144058Z kind: DNSEndpoint
2020-05-17T14:10:06.421451678Z metadata:
```
The above lines are a snippet from a pod dumping a resource.  While these lines aern't indented, when they are, the lack of fixed-width timestamps can produce confusing output.

**Environment (please complete the following information):**
- Lens Version: 3.4.0
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): brew

**Comment by Nuru** [comment]
This is a general [problem with Kubernetes](https://github.com/kubernetes/kubernetes/issues/72292), and goes all the way to the core Go library definition of the time format RFC3339Nano (see [line 71](https://golang.org/src/time/format.go)). Not something Lens can solve. 

Please vote for [fixing this in Kubernetes](https://github.com/kubernetes/kubernetes/issues/91186).

**Comment by Nuru** [comment]
This is [fixed in Kubernetes master](https://github.com/kubernetes/kubernetes/pull/91207), targeted for Kubernetes 1.19. Maybe it will get backported:
- [Kubernetes 1.18](https://github.com/kubernetes/kubernetes/pull/91351)
- [Kubernetes 1.17](https://github.com/kubernetes/kubernetes/pull/91355)
- [Kubernetes 1.16](https://github.com/kubernetes/kubernetes/pull/91356)

It could help if you voted for the PRs.

**Comment by jakolehm** [comment]
Seems to be an issue with Kubernetes.

**Comment by Nuru** [comment]
Fixed in Kubernetes:
- [1.16.12](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.16.md#v11612)
- [1.17.8](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md#v1178)
- [1.18.5-rc1](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#v1185-rc1)
