### ISSUE TITLE
cpu pod usage wrong

### ISSUE THREAD

**Issue by yagilm** [lensapp/lens#607]
When looking at the pod CPU usage, the numbers are different than in kubernetes-dashboard and `kubectl -n kube-infrastructure top pod`.

1. Go to the pod
2. Click on it
3. See the CPU usage
4. compare it with `kubectl top pod` or kubernetes dashboard
5. notice that the cpu usage is different

**Expected behavior**
The cpu usage is the same

**Environment (please complete the following information):**
- Lens Version: 3.5.1
- OS: linux
- Installation method AppImage

**Comment by nevalla** [comment]
Are you using prometheus-operator? Just noticed that it includes couple of additional kubelet services that are reporting cpu metrics too.

**Comment by dheerajinganti** [comment]
I have also noticed this today with latest 3.5.3 version. What I see in Lens is different than what I see on grafana dashboard for pod memory and cpu usage vs request/limits. In fact memory usage is shown 2x (~2 times) for a pod, looks like memory usage and memory(rss) are being added to show on Lens.

**Comment by jakolehm** [comment]
@dheerajinganti possible for you to share the used prometheus query on Grafana?

**Comment by dheerajinganti** [comment]
Here you go...

Memory usage: 
sum(container_memory_working_set_bytes{cluster="$cluster", namespace="$namespace",container!="", image!=""}) by (pod)

Memory Request: 
sum(container_memory_working_set_bytes{cluster="$cluster", namespace="$namespace",container!="", image!=""}) by (pod)

Memory Request %: 
sum(container_memory_working_set_bytes{cluster="$cluster", namespace="$namespace",container!="", image!=""}) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace="$namespace"}) by (pod)

Memory Limits:
sum(kube_pod_container_resource_limits_memory_bytes{cluster="$cluster", namespace="$namespace"}) by (pod)

Memory limit %:
sum(container_memory_working_set_bytes{cluster="$cluster", namespace="$namespace",container!="", image!=""}) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace="$namespace"}) by (pod)

Memory Usage(RSS):
sum(container_memory_rss{cluster="$cluster", namespace="$namespace",container!=""}) by (pod)

Memory Usage (cache)
sum(container_memory_cache{cluster="$cluster", namespace="$namespace",container!=""}) by (pod)


Memory usage (swap)
sum(container_memory_swap{cluster="$cluster", namespace="$namespace",container!=""}) by (pod)

**Comment by dheerajinganti** [comment]
@jakolehm does the above information helps...

**Comment by jakolehm** [comment]
@dheerajinganti yes, I think it will help. Thanks!

**Comment by aleksfront** [comment]
Can't reproduce the issue. Tested prometheus operator (kube-prometheus) and lens promQL commands, can't see any differences between values except small floated ones caused by rounding and time differences (kubernetes dashboard and lens can took their metric values at different time). Can't confirm also pod memory usage 2x comparable to `metrics-server` data.

Here's my comparison with prometheus operator:
### Memory
Lens value 
![lens pod memory usage](https://user-images.githubusercontent.com/9607060/94670819-b3c58a00-031b-11eb-9c2d-3402bfb8112a.png)
Kubernetes dashboard value
![k8s dash pod memory usage](https://user-images.githubusercontent.com/9607060/94670848-bd4ef200-031b-11eb-8da4-9d5ac0606a89.png)

### CPU
Lens value
![lens pod cpu usage](https://user-images.githubusercontent.com/9607060/94670937-e1123800-031b-11eb-89ce-3c2853e58b38.png)
Kubernetes dashboard value
![k8s pod cpu usage](https://user-images.githubusercontent.com/9607060/94670963-ecfdfa00-031b-11eb-8b80-ba6d2abe6499.png)

Also, exact numbers is observable when using lens build-in prometheus.

**Comment by aleksfront** [comment]
Grafana can also show a bit different numbers by default but I beleive there's an option to change Y-Axis unit to Mebibytes. So both commands
```
sum(container_memory_working_set_bytes{cluster="$cluster", namespace="$namespace",container!="", image!=""}) by (pod)
sum(container_memory_working_set_bytes{container!="POD",container!="",image!="",pod=~"${pods}",namespace="${namespace}"}) by (pod, namespace)
```


will show exact numbers like `metrics-server` (kubernetes dashboard does).
