### ISSUE TITLE
AppData\Roaming blocks kubectl binaries on corporate domains

### ISSUE THREAD

**Issue by leemorton** [lensapp/lens#679]
Storing the kubectl binaries in AppData\Roaming on Windows does not work on corporate domains whereby there is usually a group policy preventing save .exe files in that folder. The kubectl binary files in Windows should be saved in AppData\Local instead.

This manifests as an EPERM: operation not permitted error when connecting to a cluster and it attempts to download the kubectl binaries.

**Comment by leemorton** [comment]
#597

**Comment by webmutation** [comment]
Tracking as we have the same issue. We have only specific versions of kubectl and helm available to us via App-V (Virtual Apps) and we are not able to use different versions. Currently we can live with this since in VS Code for example we can set the path to these virtualized applications. We hope soon the same will be possible with Lens, where we can set the path to the executables and not have a Roaming profile... this will also help in making Lens portable.

**Comment by nevalla** [comment]
To solve this issue we will add mechanism to detect the situation when bundled kubectl does not work on app start and add two configuration options to global preferences:

1. Option to define path where binaries will be downloaded
2. Option to disable "smart kubectl" feature and binary downloads. Instead, user can define path to kubectl and helm3 binaries. Then, those binaries are used despite the version of Kubernetes cluster.
