### ISSUE TITLE
Show tooltip why Metrics feature can't be installed

### ISSUE THREAD

**Issue by mih-kopylov** [lensapp/lens#712]
**Describe the bug**
Install Metrics button is disabled. Can't install prometheus to see metrics. 
What am I doing wrong?

**To Reproduce**
1. Go to 'Cluster configuration'
2. Scroll down to 'Features'
3. Click on 'Install' for metrics

**Expected behavior**
Button is enabled, Prometheus is installing

**Screenshots**
![image](https://user-images.githubusercontent.com/6898003/90595014-8baf1b00-e1f4-11ea-812e-0fa9dc2ffc19.png)

**Environment (please complete the following information):**
- Lens Version: 3.5.3
- OS: Windows 10

**Comment by nevalla** [comment]
Do you have cluster-admin rights to the cluster? Installation of Metrics feature requires that.

**Comment by mih-kopylov** [comment]
@nevalla, oh, it seems I don't.

If that's the reason, it would be nice to have a comprehensive description why the button is not enabled.

**Comment by pashevskii** [comment]
@jakolehm @nevalla Hi, it seems it is fixed by [next-day commit](https://github.com/lensapp/lens/commit/5670312c474eb5b6d506a3793863707a7df76775#diff-783c3476867ba64b3c0e6e9ca4d4f96ac870fdc9d52540f4fff0c3441086ac81R69)
The [line](https://github.com/lensapp/lens/blob/f18d8618cd1a8081203c62bf901c1dbe626713a1/src/renderer/components/%2Bcluster-settings/components/install-feature.tsx#L85) fixing the issue.
Please close it
