### ISSUE TITLE
Create portforward / proxy from service

### ISSUE THREAD

**Issue by justinrush** [lensapp/lens#714]
**What would you like to be added**:
Have a shortcut way to create a port-forward to localhost from the network -> pods screen. For example, on the triple dot, add a "port-forward" in addition to shell, logs, edit and remove.

**Why is this needed**:
Sometimes I need to troubleshoot why an ingress/l4 isn't working and that means running a:
```
kubectl --namespace myns port-forward my-pod 8080:8080
```
I'd like to remove the need for using kubectl as part of normal daily development

**Environment you are Lens application on:**
Lens Version: 3.5.3
OS: Windows 10 v2004
Installation method (e.g. snap or AppImage in Linux): exe download/install
Kubernetes 1.18.6+vmware.1 on VMware Tanzu

**Comment by nevalla** [comment]
This is already possible by clicking port link in service details:
![image](https://user-images.githubusercontent.com/455844/91081703-30e04e00-e650-11ea-9d36-2f5dbc40dcb3.png)

`3.6.0` brings the same functionality to pods. We still need to improve UX to make this feature more visible to users. Something like you've suggested might be one option.

**Comment by justinrush** [comment]
Thats good enough for me at this time; certainly having it on a specific pod will help with other troubleshooting.

**Comment by jackiefong** [comment]
It will be great to have this feature and allow users to select the port number for portforward.

For example, I have a MySQL service and port 3306 ,   The current feature of port-forward will randomly assign a port.

Because the port is random, the user will have to re-config things like "MYSQL workbench connection "

**Comment by spencerhuang** [comment]
Most of us use a different tool like MySQL workbench or SQLPro or whatever tool to connect to database in docker. Lens Assigning a Random Port will create extra burden to switch the configuration of our SQL tool, which defeats the purpose of using a unified tool to begin with. Since K8s allows users to configure the ports of port-forwarding, I don't see why can't lens do it? I hope no one is switching back to k8s just because this request gets closed without feature plan.
