### ISSUE TITLE
About Lens, closed source and list of alternatives

### ISSUE THREAD

**Issue by ogarcia** [lensapp/lens#8008]
Lens has gone closed source, this is respectable, but personally I feel better supporting open source projects. Since for now there is no lens fork (and honestly I don't think there will be any in the short term), I leave here the list of alternatives I know (and many of them I package for Arch Linux in the AUR). Feel free to comment and expand the list.

- [Freelens](https://github.com/freelensapp/freelens)
- [k9s](https://k9scli.io/)
- [kdash](https://kdash.cli.rs/)
- [Headlamp](https://headlamp.dev/) (it is the application most similar to Lens)
- [Seabird](https://getseabird.github.io)

**Comment by dominch** [comment]
k8sstudio seems promising 

list of shame: kubernetic - initially license was $15 (one time), then they changed it to per month license also failing to deliver recent k8s support (it took more than 1y to fix it).

**Comment by coddy82** [comment]
Seems like k8sstudio is closed source? There's also [Infra](https://infra.app/) and [Aptakube](https://aptakube.com/) that are closed source

Aside from what has been mentioned, [OpenLens](https://github.com/MuhammedKalkan/OpenLens) still works, but it's very outdated

**Comment by msa0311** [comment]
Thanks for sharing your thoughts. We understand the importance of open-source for many users. However, this repository focuses on issues related to Lens Desktop product. While we appreciate the knowledge of alternatives, we'd like to keep our issues and discussions Lens-centric. Feel free to share any Lens-specific feedback or ideas you might have!

**Comment by nathanael-h** [comment]
There is kubenav at https://github.com/kubenav/kubenav

**Comment by DevBey** [comment]
best alternative is devtron

**Comment by CappyT** [comment]
> Thanks for sharing your thoughts. We understand the importance of open-source for many users. However, this repository focuses on issues related to Lens Desktop product. While we appreciate the knowledge of alternatives, we'd like to keep our issues and discussions Lens-centric. Feel free to share any Lens-specific feedback or ideas you might have!

With all due respect, you gave us no choice when it came to using Lens.
It felt like a "bait and switch" scheme, using Lens in an open-source manner as a lure and then switching to a subscription model once the adoption was high enough.

I understand that there might be a shift of interests and focus inside Mirantis, and thus the "close" on the source. 
I won't touch on how wrong is to receive contributions from the community and then "steal" said code to sell in a product, as I don't even know nor I am aware of the community even contributing something significant... but here we're just helping members who cannot justify switching to a subscription model (Homelabs, personal clusters, learning... etc) to have alternatives.

So we ask you kindly to not start censoring alternatives. You had your change of heart on the future of Lens. The community can have its change of heart too.

Thanks for understanding and comprehension.

**Comment by huseyinbabal** [comment]
[Monokle](https://github.com/kubeshop/monokle), it also has SaaS version

**Comment by desaintmartin** [comment]
Given that Mirantis is stating "doubling down on open source" (https://thenewstack.io/kubecon24-mirantis-doubles-down-on-open-source/), will we see Lens going open source again ?

**Comment by techdragon** [comment]
I'll be surprised if Mirantis actually change course.

**Comment by cr1cr1** [comment]
Tried all the open source from above, and others: Monokle, Kubenav, Rancher, Headlamp, Jet Pilot.

And tried again after some months (towards an year), with the idea that things will improve. None of them reaches (for me) the productivity level of OpenLens and K9S and plain old kubectl+stern. And most of them will never improve, because I think the UX design decisions are... well, weird and unwieldy. Headlamp is particularly slow and most of the times it does not work.

Kui is interesting as a concept, but meh.

Most of them are confusing to use, I have to dig for stuff, basic filtering missing, some do not even have search. Overall, from an UX perspective, they suck.

Also, Kubernetes Dashboard made a comeback. Granted, not an IDE, it is deployed in the cluster, but... it works just fine. Then again, I apply gitops principles since more than 7 years now, I do not directly handle objects in a k8s cluster.

VSCode + kubernetes plugin is decent as it is the unmaintained Weaveworks gitops plugin (I use FluxCD so it is convenient for me).

Also, what's with the monthly subscription for some of the other K8S GUIs that offer little more than pretty colors for what is a simple DAG of k8s objects and an YAML editor ? :) Well, I guess this is the defacto business model nowadays.

**Comment by swatimehta26** [comment]
I'm using kubewall https://github.com/kubewall/kubewall It's pretty new but does the job just fine.
It's a single binary browser-based k8s dashboard.

**Comment by olstjos** [comment]
Headlamp is very good! https://headlamp.dev/

**Comment by UncleSamSwiss** [comment]
Just found [Freelens](https://github.com/freelensapp/freelens)
Thanks to @robertobandini in https://github.com/MuhammedKalkan/OpenLens/issues/198#issuecomment-2614050641

**Comment by jleni** [comment]
Adding one to the list: **Kunobi**. Built with Tauri/Rust instead of Electron — no bloat, no forced login, just reads your kubeconfig. Works on macOS, Windows, and Linux.

Still early stages but moving fast. Already has native Flux CD and ArgoCD support, and it's expanding beyond just K8s management.

@cr1cr1 — if you're still stuck with the unmaintained Weaveworks GitOps plugin for Flux, this might be worth a look. Free tier available.

**Comment by marafa-sugarcrm** [comment]
i cant find the code for kunobi. and the download is not from github but from their corporate website. it looks like it could be a repeat of openlens. i will stick with freelens

**Comment by ogarcia** [comment]
> i cant find the code for kunobi. and the download is not from github but from their corporate website. it looks like it could be a repeat of openlens. i will stick with freelens

Agree. Furthermore, in Kunobi web page says **Free During Beta** so is not open source nor relevant here.

**Comment by nadaverell** [comment]
All this time and still no good enough go-to solution. 

So we created Radar - https://github.com/skyhook-io/radar - 15 seconds to try it yourself!

Fully OSS.
Everything you loved about lens and more. Local-first. No account. No cloud dependency. Blazing Fast.

Resource Topology, event timeline, service traffic visualization, helm management in addition to the best core resource management experience.

**Comment by sebandgo** [comment]
Lens made it impossible to use even the free version, so I built PodSteer ([Website](https://podsteer.com/), [GitHub](https://github.com/podsteer/podsteer)) an open-source tool that just does it's job properly.

**Comment by nadaverell** [comment]
> Lens made it impossible to use even the free version, so I built PodSteer ([Website](https://podsteer.com/), [GitHub](https://github.com/podsteer/podsteer)) an open-source tool that just does it's job properly.

instead of a new project... come contribute to radar. 3.2k stars and growing quickly. join us!

**Comment by sebandgo** [comment]
> > Lens made it impossible to use even the free version, so I built PodSteer ([Website](https://podsteer.com/), [GitHub](https://github.com/podsteer/podsteer)) an open-source tool that just does it's job properly.
> 
> instead of a new project... come contribute to radar. 3.2k stars and growing quickly. join us!

All the best with Radar.

**Comment by nadaverell** [comment]
> > > Lens made it impossible to use even the free version, so I built PodSteer ([Website](https://podsteer.com/), [GitHub](https://github.com/podsteer/podsteer)) an open-source tool that just does it's job properly.
> > 
> > 
> > instead of a new project... come contribute to radar. 3.2k stars and growing quickly. join us!
> 
> All the best with Radar.

And to you with PodSteer! It's good to see innovation in this space
