### ISSUE TITLE
Please revert the changes to search 

### ISSUE THREAD

**Issue by darkpixel** [lensapp/lens#8015]
**What would you like to be added**:
The new search is horrible for efficiency.

**Why is this needed**:
It adds more clicks and doesn't really save any screen real estate.

Instead of simply clicking in a field at the top of the page, now I have to click a magnifying glass icon, then go to the complete opposite edge of the page (bottom) and click inside a search box to start searching.

Please go back to *click* *type*.

Same with the hamburger menu.  Now instead of going to File -> Slide down to Exit, I have to go to Hamburger -> slide down to File -> Slide over to the file menu -> Slide down to exit.

**Comment by Deltids** [comment]
I mean, this change is so strange. Who in their right mind tought that this was a good idea? At least the "pin" has to keep the bar open AT ALL TIMES.

**Comment by ReggieCarey** [comment]
I completely agree.  As a paying customer. I'm more and more frustrated with the lack of human factors engineering in the UI design.  It feels like instead of choosing the best solution for an interaction, the worst solution for an interaction seems to make it into this product.  You've got a check box to select an item.  What do you do with it? Bring up some non standard UI components NO WHERE NEAR THE CHECKBOX to give users the ability to delete.  As if this wasn't already in the Hamburger on the far right of the screen.

**Comment by KeyPerformanceGroup** [comment]
This new search bar is a shame ! Hope it will be revert as soon as possible !

**Comment by darkpixel** [comment]
I'm not a UI designer.  You should see the way I dress.  And also this picture.

![badlayout](https://github.com/lensapp/lens/assets/158380/ff2c08d3-72b1-41e8-9f01-a0cbe0848dbd)

Seriously...please fix the UI/UX.

Oh, and the "namespaces" dropdown is horrible too.  Why do I get "sliding switches" only *AFTER* I click on the first namespace and the menu disappears.  What was wrong with the old menu that let me CTRL+click to select namespaces without having to click the first one, have the menu close, then re-open the menu, then click a handful of sliders?

**Comment by darkpixel** [comment]
Zero response from the devs in over four months.  I cancelled my subscription.

**Comment by jakolehm** [comment]
The search input has been improved:

<img width="1919" alt="image" src="https://github.com/user-attachments/assets/bddd1ed7-9ae2-488f-a52e-92b25a218c25">
