### ISSUE TITLE
Lens Stuck on "Activating Lens Desktop"

### ISSUE THREAD

**Issue by maviterlikli** [lensapp/lens#8077]
**Describe the bug**
When Lens is launched, the "Welcome to Lens" screen appears. However, when "New to Lens" or "Already have an Lens ID" is clicked it is stuck on "Activating Lens Desktop".

**To Reproduce**
Note: I do not think it will be reproducible in any environment.
1. Open Lens
2. Click on "New to Lens" or "Already have an Lens ID"
3. See that it is stuck on "Activating Lens Desktop"

**Expected behavior**
It should be able to log me in

**Screenshots**
![image](https://github.com/user-attachments/assets/7356af36-44a8-4446-99c1-473814199b4b)

**Environment (please complete the following information):**
- Lens Version: 2024.7.161041-latest
- OS: Ubuntu 22.04.4 LTS, daily updated
- Installation method (e.g. snap or AppImage in Linux): When the error occurred, the apt package manager is used. To debug I have tried AppArmor and Snap without any success.

**Logs:**
When you run the application executable from the command line you will see some logging output. Please paste them here:
I have run lens-desktop with DEBUG=true. Logs are too long I am adding as file. 
[LensDebugLog.txt](https://github.com/user-attachments/files/16423725/LensDebugLog.txt)

**Kubeconfig:**
I have removed every kubeconfig from Lens. The issue persists. 

**Additional context**
I have tried several things without any success.
- I have triggered Lens from the browser after logging in to my account from https://app.k8slens.dev/lens-launcher link. I tried this in Firefox and Chrome
- I have changed the default browser and retried launching Lens. Browsers: Chrome Firefox
- I have tried Snap, AppArmor, and Apt as installation methods. Used `apt purge`.
- I have cleaned `~/.config/Lens` and `~/.k8slens` and deleted `~/.kube/config`.
- I suspected some GUI things so changed to Wayland from Xorg. I redone the Xorg config. No success.

**Comment by Tixon123** [comment]
Hello maviterlikli,

 Thank you for reaching out to Lens support!

 Thank you for reporting a bug. 

 We are working on your issue. Stand by for further updates. 

Best Regards,
Tikhon Kudinov
Lens Support Engineer
Mirantis, Inc

**Comment by AntonNos** [comment]
Hello maviterlikli,

Did you try clicking "web browser"? It should open a page for activation. After activating, Lens should open successfully.

Best regards,
Anton Nos
Software Engineer
Mirantis, Inc.

**Comment by maviterlikli** [comment]
I did it in several other installations. It did not open a browser page. I have just retired it with Firefox and Chrome as the default web browser.

**Comment by AntonNos** [comment]
Please follow the instructions.

1. When you see "Activating Lens Desktop", press Ctrl+Shift+I to open the developer tools.
2. Click on the "Console" tab and then clear the console outputs. (Check the attached screenshot)
3. Click the "web browser" button in "Activating Lens Desktop".

Please take a screenshot or copy everything you see in the console.

<img width="487" alt="Screenshot 2024-07-30 at 17 42 12" src="https://github.com/user-attachments/assets/143975d1-35c7-4551-9fa8-f14e7674c811">

**Comment by maviterlikli** [comment]
Okay. With the console, I was able to debug it. It gave me my local IP as "27.0.0.1" and the connection failed to that IP since it was wrong. My /etc/hosts file has the "127.0.0.1" as "27.0.0.1". So a human error. Right now, calls are working, and I have been able to log in to my Lens account. 
![image](https://github.com/user-attachments/assets/3ec0cc10-fee4-4c72-9d0b-166355517e8e)

I am really sorry about the inconvenience since I was the root cause. If you need anything, I can help you.

**Comment by AntonNos** [comment]
No worries!
I am glad that the problem is solved.
Don't hesitate to contact support if you have any issues.

Best regards,
Anton Nos
Software Engineer
Mirantis, Inc.

**Comment by drakgoku** [comment]
I can't click anything.
![image](https://github.com/user-attachments/assets/d4497e74-642e-4bf8-88ee-1c0d105cde8b)

I'm pretty pissed off. Why? When 5-10 things fail and one of them is just a simple dashboard... it's a pain in the ass.

Now I will have to wait for 2 types of answers:
1 - The one they never answer
2 - The one they tell you to restart, reinstall or put n commands

It's unfortunate.

**Comment by maviterlikli** [comment]
First of all, Drakgoku, they are not here to solve your problems, but to make their software better while solving issues that users face. This is how opensource software works. The other best side of opensource is you do not have to use it. 

Secondly, all the process that you whine is to eliminate stupid errors and to make sure the issue is isolated to the software. So, rebooting, restarting, etc is essential. As you can see in my case the error is caused by MY wrong entry in the local DNS server. So nothing related to the Lens software. This might be your case as well. If you wish to check simply run 'nslookup localhost' at any terminal. The debug console in mention will also solve most of the issues that are not related the software. 

Lastly, if you cannot found any other issues in your system, and if you can isolate the issue, I am pretty sure they will be happy to help as long as you provide them with good input. Otherwise, it is a witch-hunt. 

Please remember that, this is not a paid software support center. This place is for open source issue submission.

**Comment by drakgoku** [comment]
We are going to differ quite a bit.

First

`they are not here to solve your problems`


I would like my argument not to be trivialized with your argument when this is a Lens problem and known from what I have seen.
Google: Lens stuck on desktop

`The other best side of opensource is you do not have to use it.`

Correct, that's why I use helm, as the documentation specifies.
https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/

I just tried to try other solutions and they recommended Lens. It could have been chips, but it was Lens.

Second
`all the process that you whine is to eliminate stupid errors and to make sure the issue is isolated to the software. So, rebooting, restarting, etc is essential. `

I have reinstalled 5 times, none of them worked.
I would like to help you, but for some reason, your application does not have logs or I don't know where they are. https://i.imgur.com/zobj0vb.png

I know it's an opensource and the limitation of resources to solve the problem. I'm aware. If it had been a paid program, we wouldn't have had this cordial chat. Believe me, it's a fact.

**Comment by drakgoku** [comment]
We are going to differ quite a bit.

First

`they are not here to solve your problems`


I would like my argument not to be trivialized with your argument when this is a Lens problem and known from what I have seen.
Google: Lens stuck on desktop

`The other best side of opensource is you do not have to use it.`

Correct, that's why I use helm, as the documentation specifies.
https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/

I just tried to try other solutions and they recommended Lens. It could have been chips, but it was Lens.

Second
`all the process that you whine is to eliminate stupid errors and to make sure the issue is isolated to the software. So, rebooting, restarting, etc is essential. `

I have reinstalled 5 times, none of them worked.

First run
I don't put everything because there are things like keys and others that I don't want to be seen.
<details>
  <summary>lens.log</summary>
Individual runnables took:
- lens-core-main:initialize-extensions                                  	15346.37 ms
- lens-core-main:show-loading                                           	6647.71 ms 
- lens-core-main:fixup-package-json                                     	4701.77 ms 
- lens-core-main:load-hotbar-storage                                    	3222.38 ms 
- lens-core-main:load-table-storage                                     	3214.77 ms 
- lens-core-main:start-reactive-tray-menu-icon                          	3211.72 ms 
- lens-core-main:start-reactive-tray-menu-items                         	3204.32 ms 
- electron:start-syncing-theme-from-operating-system                    	403.24 ms  
- electron:setup-quit-on-power-shutdown                                 	401.16 ms  
- messaging:start-listening-of-channels                                 	398.86 ms  
- user-preferences-main-feature:setup-sync-open-at-login-with-os        	387.74 ms  
- theme-main-feature:setup-system-theme-type-updater-emitter            	384.09 ms  
- cluster-connection-telemetry:start-tracking-cluster-connection-changes	382.94 ms  
- lens-core-main:initialize-cluster-manager                             	381.55 ms  
- lens-core-main:setup-deep-linking                                     	379.41 ms  
- lens-core-main:setup-developer-tools-in-development-environment       	374.19 ms  
- lens-core-main:setup-ipc-main-handlers                                	373.96 ms  
- lens-core-main:setup-main-window-visibility-after-activation          	371.93 ms  
- lens-core-main:start-application-menu                                 	371.55 ms  
- lens-core-main:start-watching-if-update-should-happen-on-quit         	371.1 ms   
- lens-core-main:init-file-system-provisioner-store                     	370.46 ms  
- lens-core-main:setup-syncing-of-general-catalog-entities              	367.23 ms  
- lens-core-main:setup-shell                                            	360.92 ms  
- lens-core-main:load-weblink-storage                                   	359.78 ms  
- lens-core-main:setup-syncing-of-weblinks                              	352.73 ms  
- lens-core-main:start-tray                                             	38.28 ms   
- lens-license:setup-lens-license                                       	1.41 ms    
info: [CREATE-ELECTRON-WINDOW]: Loading content for window "first-application-window" from url: https://lens.app:53779...
info: [CLI] inspecting registry
info: [RUN-MANY-PERFORMANCE-LOGGING]: Running runnables for "after-window-is-opened" took 204.94 ms.

Individual runnables took:
- lens-core-main:show-dock-for-first-opened-window	39.33 ms
debug: [CLOUD-SYNC-REPORTER]: [CLOUD-PROVIDER-SYNC] has cloud provider clis: aws
info: [KUBECONFIG-SYNC]: starting requested syncs
info: [KUBECONFIG-SYNC]: starting sync of file/folder {"filePath":"C:\\Users\\........\\AppData\\Roaming\\Lens\\kubeconfigs"}
debug: [KUBECONFIG-SYNC]: 1 files/folders watched {"files":["C:\\Users\\........\\AppData\\Roaming\\Lens\\kubeconfigs"]}
info: [KUBECONFIG-SYNC]: starting sync of file/folder {"filePath":"C:\\Users\\........\\.kube"}
debug: [KUBECONFIG-SYNC]: 2 files/folders watched {"files":["C:\\Users\\........\\AppData\\Roaming\\Lens\\kubeconfigs","C:\\Users\\........\\.kube"]}
debug: [KUBECONFIG-SYNC]: file changed {"filePath":"C:\\Users\\........\\.kube\\config"}
warn: [KUBECONFIG-SYNC]: encountered errors while loading config {"details":[{"code":"invalid_type","expected":"array","message":"Expected array, received null","path":["users"],"received":"null"},{"code":"invalid_type","expected":"array","message":"Expected array, received null","path":["clusters"],"received":"null"},{"code":"invalid_type","expected":"array","message":"Expected array, received null","path":["contexts"],"received":"null"}],"filePath":"C:\\Users\\........\\.kube\\config"}
debug: [KUBECONFIG-SYNC]: File now has 0 entries {"filePath":"C:\\Users\\........\\.kube\\config"}
debug: [KUBECONFIG-SYNC]: Finished computing diff {"filePath":"C:\\Users\\........\\.kube\\config"}
info: [CREATE-ELECTRON-WINDOW]: Window "first-application-window" loaded
debug: [TIP-STORE]: syncing tip-store.json {"model":{"__internal__":{"migrations":{"version":"1.13.2"}},"activeSteps":{"lens-desktop-kube":0,"lens-desktop-kube-profiles":0,"support-extension":0,"teamwork-preferences":0,"teamwork-topbar-add-cluster":0,"teamwork-topbar-invite-user":0},"skipAll":false}}
info: [RUN-MANY-PERFORMANCE-LOGGING]: Running runnables for "after-application-is-loaded-injection-token" took 19008.31 ms.

Individual runnables took:
- lens-core-main:show-initial-window                 	18895.17 ms
- cli-feature:cli-register-win32-path                	5147.6 ms  
- lens-core-main:start-kubeconfig-sync               	2394.75 ms 
- cloud-sync-reporter:report-cloud-clis              	403.03 ms  
- lens-core-main:start-checking-for-updates          	248.47 ms  
- lens-core-main:emit-current-version-to-analytics   	230.38 ms  
- lens-core-main:emit-service-start-to-event-bus     	226.66 ms  
- lens-core-main:add-kubeconfig-sync-as-entity-source	223.35 ms  
- cli-feature:lens-cli-initialize-server             	196.74 ms  
info: [RUN-MANY-PERFORMANCE-LOGGING]: Running runnables for "after-root-frame-is-ready" took 13.54 ms.

Individual runnables took:
- lens-core-main:start-catalog-sync     	11.93 ms
- lens-core-main:flag-renderer-as-loaded	0.92 ms 
</details>


<details>
  <summary>lens-renderer-root-frame.log</summary>
info: [RUN-MANY-PERFORMANCE-LOGGING]: Running runnables for "before-main-frame-starts-second" took 0.1 ms.

Individual runnables took:

info: [EXTENSIONS-LOADER]: auto initializing extensions
info: [CLI] activated
info: [TIP-STORE]: LOADING ...
info: [TIP-STORE]: LOADED from C:\Users\.....\AppData\Roaming\Lens\extension-store\tour-lens-extension\tip-store.json
info: [SECURITY-PREFERENCES-STORE]: LOADING ...
info: [SECURITY-PREFERENCES-STORE]: LOADED from C:\Users\.....\AppData\Roaming\Lens\extension-store\oci-image-lens-extension\security-preferences-store.json
info: [SUPPORT-EXTENSION] activated
info: [PREFERENCES-STORE]: LOADING ...
info: [PREFERENCES-STORE]: LOADED from C:\Users\.....\AppData\Roaming\Lens\extension-store\survey-lens-extension\preferences-store.json
info: [PREFERENCES-STORE]: LOADING ...
info: [PREFERENCES-STORE]: LOADED from C:\Users\.....\AppData\Roaming\Lens\extension-store\telemetry-lens-extension\preferences-store.json
info: [LDK-STORE]: LOADING ...
info: [LDK-STORE]: LOADED from C:\Users\.....\AppData\Roaming\Lens\extension-store\lens-desktop-kube-lens-extension\ldk-store.json
info: [LENS-APPS] activated
info: [LOCAL-METADATA-STORE]: LOADING ...
info: [LOCAL-METADATA-STORE]: LOADED from C:\Users\.....\AppData\Roaming\Lens\extension-store\lenscloud-lens-extension\local-metadata-store.json
info: [RELEASE-NOTES-STORE]: LOADING ...
info: [RELEASE-NOTES-STORE]: LOADED from C:\Users\.....\AppData\Roaming\Lens\extension-store\lenscloud-lens-extension\release-notes-store.json
info: [GRACE-PERIOD-STORE]: LOADING ...
info: [GRACE-PERIOD-STORE]: LOADED from C:\Users\.....\AppData\Roaming\Lens\extension-store\lenscloud-lens-extension\grace-period-store.json
info: [END-OF-TRIAL-STORE]: LOADING ...
info: [END-OF-TRIAL-STORE]: LOADED from C:\Users\.....\AppData\Roaming\Lens\extension-store\lenscloud-lens-extension\end-of-trial-store.json
info: [SPACES-SETTINGS-STORE]: LOADING ...
info: [SPACES-SETTINGS-STORE]: LOADED from C:\Users\.....\AppData\Roaming\Lens\extension-store\lenscloud-lens-extension\spaces-settings-store.json
info: [LENS-SPACES-EXTENSION]: 15/9/2024, 0:45:12 Lens Spaces Extension activated
info: [EXTENSION]: enabled @lensapp/cli-lens-extension@0.21.1
info: [EXTENSION]: enabled @lensapp/cluster-metrics@7.1.31
info: [EXTENSION]: enabled @lensapp/kube-event-statuses@1.0.33
info: [EXTENSION]: enabled @lensapp/lenscloud-lens-extension@2.3.0
info: [EXTENSION]: enabled @lensapp/node-menu@7.0.34
info: [EXTENSION]: enabled @lensapp/pod-menu@7.0.34
info: [EXTENSION]: enabled @lensapp/lens-desktop-kube-lens-extension@0.36.4
info: [EXTENSION]: enabled @lensapp/lens-license-extension@0.19.2
info: [EXTENSION]: enabled @lensapp/oci-image-lens-extension@0.36.2
info: [EXTENSION]: enabled @lensapp/shipa-lens-extension@0.23.5
info: [EXTENSION]: enabled @lensapp/support-lens-extension@0.16.2
info: [EXTENSION]: enabled @lensapp/survey-lens-extension@0.11.2
info: [EXTENSION]: enabled @lensapp/telemetry-lens-extension@0.13.4
info: [EXTENSION]: enabled @lensapp/tour-lens-extension@1.13.2
info: [PROTOCOL ROUTER]: internal registering /preferences
info: [PROTOCOL ROUTER]: internal registering /
info: [PROTOCOL ROUTER]: internal registering /landing
info: [PROTOCOL ROUTER]: internal registering /landing/view/:group/:kind
info: [PROTOCOL ROUTER]: internal registering /cluster
info: [PROTOCOL ROUTER]: internal registering /entity/:entityId/settings
info: [PROTOCOL ROUTER]: internal registering /open/:connectionType/:clusterSpecifier/:frame
info: [PROTOCOL ROUTER]: internal registering /cluster/:clusterId
info: [PROTOCOL ROUTER]: internal registering /cluster/:clusterId/settings
info: [PROTOCOL ROUTER]: internal registering /extensions
info: [PROTOCOL ROUTER]: internal registering /extensions/install/:LENS_INTERNAL_EXTENSION_PUBLISHER_MATCH(@[A-Za-z0-9_]+)?/:LENS_INTERNAL_EXTENSION_NAME_MATCH
info: [RUN-MANY-PERFORMANCE-LOGGING]: Running runnables for "on-load-of-application" took 8254.2 ms.

Individual runnables took:
- lens-core-renderer:bootstrap                                   	7621.9 ms
- lens-core-renderer:start-frame                                 	617 ms   
- lens-core-renderer:updating-is-enabled-initialization          	255.5 ms 
- messaging:start-listening-of-channels                          	170.4 ms 
- messaging-for-renderer:allow-communication-to-iframe-injectable	156.5 ms 
info: [RUN-MANY-PERFORMANCE-LOGGING]: Running runnables for "after-application-is-loaded-injection-token" took 462.4 ms.

Individual runnables took:
- react-application:render-application-when-application-is-ready	459.3 ms
- lens-core-renderer:register-chart-injectable                  	13.6 ms 
- chart-plugins:register-annotation-injectable                  	12.2 ms 
- chart-plugins:register-highest-max-injectable                 	11.8 ms 
- chart-plugins:register-moment-adapter-injectable              	11.6 ms 
- chart-plugins:register-zoom-plugin-injectable                 	11.2 ms 


</details>

Only reopen

<details>
  <summary>lens-renderer-root-frame.log</summary>

info: [CREATE-ELECTRON-WINDOW]: Loading content for window "splash" from file: E:\Tools\Lens\resources\app.asar\static\splash.html...
info: [RUN-MANY-PERFORMANCE-LOGGING]: Running runnables for "after-window-is-opened" took 14.48 ms.

Individual runnables took:
- lens-core-main:show-dock-for-first-opened-window	0.13 ms
info: [CREATE-ELECTRON-WINDOW]: Window "splash" loaded
info: [CREATE-ELECTRON-WINDOW]: Loading content for window "first-application-window" from url: https://lens.app:53779...
info: [RUN-MANY-PERFORMANCE-LOGGING]: Running runnables for "after-window-is-opened" took 13.22 ms.

Individual runnables took:
- lens-core-main:show-dock-for-first-opened-window	0.15 ms
info: [CREATE-ELECTRON-WINDOW]: Window "first-application-window" loaded
debug: [TIP-STORE]: syncing tip-store.json {"model":{"__internal__":{"migrations":{"version":"1.13.2"}},"activeSteps":{"lens-desktop-kube":0,"lens-desktop-kube-profiles":0,"support-extension":0,"teamwork-preferences":0,"teamwork-topbar-add-cluster":0,"teamwork-topbar-invite-user":0},"skipAll":false}}
info: [RUN-MANY-PERFORMANCE-LOGGING]: Running runnables for "after-root-frame-is-ready" took 0.34 ms.

Individual runnables took:
- lens-core-main:start-catalog-sync     	11.93 ms
- lens-core-main:flag-renderer-as-loaded	0.92 ms 

</details>

<details>
  <summary>lens-renderer-root-frame.log</summary>
info: [LENS-CORE-RENDERER]: loading finished for C:\Users\.........\AppData\Roaming\Lens\lens-local-storage\app.json
info: [RUN-MANY-PERFORMANCE-LOGGING]: Running runnables for "before-application-is-loading-injection-token" took 183 ms.

Individual runnables took:
- lens-core-renderer:initialize-lens-local-storage-state	151 ms 
- app-paths-setup-renderer:setup-app-paths              	17.3 ms
info: [RUN-MANY-PERFORMANCE-LOGGING]: Running runnables for "before-frame-starts-first" took 276.6 ms.

Individual runnables took:
- lens-core-renderer:setup-lens-proxy-certificate	262.4 ms
- lens-core-renderer:preload-terminal-fonts      	262 ms  
- lens-core-renderer:configure-immer             	199.2 ms
- lens-core-renderer:configure-mobx              	197.9 ms
info: [RUN-MANY-PERFORMANCE-LOGGING]: Running runnables for "before-main-frame-starts-first" took 5.9 ms.

Individual runnables took:
- lens-core-renderer:setup-current-cluster-broadcast	4.9 ms
- lens-core-renderer:setup-sentry                   	1.2 ms
info: [LENS-USER-STORE]: LOADING ...
info: [LENS-USER-STORE]: LOADED from C:\Users\.........\AppData\Roaming\Lens\lens-user-store.json
info: [LENS-FILESYSTEM-PROVISIONER-STORE]: LOADING ...
info: [LENS-FILESYSTEM-PROVISIONER-STORE]: LOADED from C:\Users\.........\AppData\Roaming\Lens\lens-filesystem-provisioner-store.json
info: [LENS-WEBLINK-STORE]: LOADING ...
info: [LENS-WEBLINK-STORE]: LOADED from C:\Users\.........\AppData\Roaming\Lens\lens-weblink-store.json
info: [LENS-CLUSTER-STORE]: LOADING ...
info: [LENS-CLUSTER-STORE]: LOADED from C:\Users\.........\AppData\Roaming\Lens\lens-cluster-store.json
info: [LENS-HOTBAR-STORE]: LOADING ...
info: [LENS-HOTBAR-STORE]: LOADED from C:\Users\.........\AppData\Roaming\Lens\lens-hotbar-store.json
info: [LENS-TABLE-STORE]: LOADING ...
info: [LENS-TABLE-STORE]: LOADED from C:\Users\.........\AppData\Roaming\Lens\lens-table-store.json
info: [LENS-EXTENSIONS]: LOADING ...
info: [LENS-EXTENSIONS]: LOADED from C:\Users\.........\AppData\Roaming\Lens\lens-extensions.json
info: [RUN-MANY-PERFORMANCE-LOGGING]: Running runnables for "before-frame-starts-second" took 432.8 ms.

Individual runnables took:
- lens-core-renderer:provide-initial-values-for-sync-boxes                       	292 ms  
- lens-core-renderer:enabled-extensions-persistent-storage-version-initialization	290.9 ms
- theme-renderer-feature:initialize-system-theme-type                            	290.6 ms
- lens-core-renderer:setup-system-ca                                             	288.3 ms
- lens-core-renderer:setup-cluster-state-sync                                    	286 ms  
- user-preferences-renderer-feature:load-user-preferences-storage                	126 ms  
- lens-core-renderer:listen-unload                                               	42.7 ms 
- lens-core-renderer:load-monaco-themes                                          	42.2 ms 
- lens-core-renderer:setup-kubernetes-cluster-catalog-add-menu-listener          	22.5 ms 
- lens-core-renderer:setup-kubernetes-cluster-context-menu-open                  	20.2 ms 
- lens-core-renderer:setup-root-mac-classname                                    	17.1 ms 
- lens-core-renderer:setup-weblink-context-menu-open                             	16.7 ms 
- lens-core-renderer:start-topbar-state-sync                                     	16.5 ms 
- lens-core-renderer:init-file-system-provisioner-store                          	15.6 ms 
- lens-core-renderer:listen-cluster-frame-sleep-resume                           	13.4 ms 
- lens-core-renderer:load-hotbar-storage                                         	13.2 ms 
- lens-core-renderer:load-weblink-storage                                        	10.5 ms 
- lens-core-renderer:init-cluster-store                                          	10.4 ms 
- lens-core-renderer:load-enabled-extensions-storage                             	5.8 ms  
- theme-renderer-feature:setup-apply-active-theme                                	5.7 ms  
- lens-core-renderer:load-table-storage                                          	4 ms    
- lens-core-renderer:setup-logging-for-navigation                                	2.2 ms  
info: [RUN-MANY-PERFORMANCE-LOGGING]: Running runnables for "before-main-frame-starts-second" took 0.1 ms.

Individual runnables took:

info: [EXTENSIONS-LOADER]: auto initializing extensions
info: [CLI] activated
info: [TIP-STORE]: LOADING ...
info: [TIP-STORE]: LOADED from C:\Users\.........\AppData\Roaming\Lens\extension-store\tour-lens-extension\tip-store.json
info: [SECURITY-PREFERENCES-STORE]: LOADING ...
info: [SECURITY-PREFERENCES-STORE]: LOADED from C:\Users\.........\AppData\Roaming\Lens\extension-store\oci-image-lens-extension\security-preferences-store.json
info: [SUPPORT-EXTENSION] activated
info: [PREFERENCES-STORE]: LOADING ...
info: [PREFERENCES-STORE]: LOADED from C:\Users\.........\AppData\Roaming\Lens\extension-store\survey-lens-extension\preferences-store.json
info: [PREFERENCES-STORE]: LOADING ...
info: [PREFERENCES-STORE]: LOADED from C:\Users\.........\AppData\Roaming\Lens\extension-store\telemetry-lens-extension\preferences-store.json
info: [LDK-STORE]: LOADING ...
info: [LDK-STORE]: LOADED from C:\Users\.........\AppData\Roaming\Lens\extension-store\lens-desktop-kube-lens-extension\ldk-store.json
info: [LENS-APPS] activated
info: [LOCAL-METADATA-STORE]: LOADING ...
info: [LOCAL-METADATA-STORE]: LOADED from C:\Users\.........\AppData\Roaming\Lens\extension-store\lenscloud-lens-extension\local-metadata-store.json
info: [RELEASE-NOTES-STORE]: LOADING ...
info: [RELEASE-NOTES-STORE]: LOADED from C:\Users\.........\AppData\Roaming\Lens\extension-store\lenscloud-lens-extension\release-notes-store.json
info: [GRACE-PERIOD-STORE]: LOADING ...
info: [GRACE-PERIOD-STORE]: LOADED from C:\Users\.........\AppData\Roaming\Lens\extension-store\lenscloud-lens-extension\grace-period-store.json
info: [END-OF-TRIAL-STORE]: LOADING ...
info: [END-OF-TRIAL-STORE]: LOADED from C:\Users\.........\AppData\Roaming\Lens\extension-store\lenscloud-lens-extension\end-of-trial-store.json
info: [SPACES-SETTINGS-STORE]: LOADING ...
info: [SPACES-SETTINGS-STORE]: LOADED from C:\Users\.........\AppData\Roaming\Lens\extension-store\lenscloud-lens-extension\spaces-settings-store.json
info: [LENS-SPACES-EXTENSION]: 15/9/2024, 0:50:11 Lens Spaces Extension activated
info: [EXTENSION]: enabled @lensapp/cli-lens-extension@0.21.1
info: [EXTENSION]: enabled @lensapp/cluster-metrics@7.1.31
info: [EXTENSION]: enabled @lensapp/kube-event-statuses@1.0.33
info: [EXTENSION]: enabled @lensapp/lenscloud-lens-extension@2.3.0
info: [EXTENSION]: enabled @lensapp/node-menu@7.0.34
info: [EXTENSION]: enabled @lensapp/pod-menu@7.0.34
info: [EXTENSION]: enabled @lensapp/lens-desktop-kube-lens-extension@0.36.4
info: [EXTENSION]: enabled @lensapp/lens-license-extension@0.19.2
info: [EXTENSION]: enabled @lensapp/oci-image-lens-extension@0.36.2
info: [EXTENSION]: enabled @lensapp/shipa-lens-extension@0.23.5
info: [EXTENSION]: enabled @lensapp/support-lens-extension@0.16.2
info: [EXTENSION]: enabled @lensapp/survey-lens-extension@0.11.2
info: [EXTENSION]: enabled @lensapp/telemetry-lens-extension@0.13.4
info: [EXTENSION]: enabled @lensapp/tour-lens-extension@1.13.2
info: [PROTOCOL ROUTER]: internal registering /preferences
info: [PROTOCOL ROUTER]: internal registering /
info: [PROTOCOL ROUTER]: internal registering /landing
info: [PROTOCOL ROUTER]: internal registering /landing/view/:group/:kind
info: [PROTOCOL ROUTER]: internal registering /cluster
info: [PROTOCOL ROUTER]: internal registering /entity/:entityId/settings
info: [PROTOCOL ROUTER]: internal registering /open/:connectionType/:clusterSpecifier/:frame
info: [PROTOCOL ROUTER]: internal registering /cluster/:clusterId
info: [PROTOCOL ROUTER]: internal registering /cluster/:clusterId/settings
info: [PROTOCOL ROUTER]: internal registering /extensions
info: [PROTOCOL ROUTER]: internal registering /extensions/install/:LENS_INTERNAL_EXTENSION_PUBLISHER_MATCH(@[A-Za-z0-9_]+)?/:LENS_INTERNAL_EXTENSION_NAME_MATCH
info: [RUN-MANY-PERFORMANCE-LOGGING]: Running runnables for "on-load-of-application" took 7989.8 ms.

Individual runnables took:
- lens-core-renderer:bootstrap                                   	7247.5 ms
- lens-core-renderer:start-frame                                 	723.8 ms 
- lens-core-renderer:updating-is-enabled-initialization          	267 ms   
- messaging:start-listening-of-channels                          	227.1 ms 
- messaging-for-renderer:allow-communication-to-iframe-injectable	200.1 ms 
info: [RUN-MANY-PERFORMANCE-LOGGING]: Running runnables for "after-application-is-loaded-injection-token" took 452.3 ms.

Individual runnables took:
- react-application:render-application-when-application-is-ready	447.7 ms
- lens-core-renderer:register-chart-injectable                  	12.4 ms 
- chart-plugins:register-annotation-injectable                  	10.4 ms 
- chart-plugins:register-highest-max-injectable                 	9.7 ms  
- chart-plugins:register-moment-adapter-injectable              	9.4 ms  
- chart-plugins:register-zoom-plugin-injectable                 	9.1 ms  

</details>

I know it's an opensource and the limitation of resources to solve the problem. I'm aware.

My problem is that it doesn't stay stuck when I try to activate it in the product. When I turn on Lens (double click on the icon) it makes it look like it's loading and when I try to select something I can't. That is, I can't click on anything.

**Comment by panuhorsmalahti** [comment]
@drakgoku I think your bug is a new one, I haven't seen this one before (e.g. UI completely stuck in this screen). Does any of the application menus work, like showing About lens, opening preferences or the license?

**Comment by drakgoku** [comment]
No, no matter what I do, nothing works.
I've seen this:
https://recoverit.wondershare.com/computer-problems/windows-10-stuck-on-welcome-screen.html
But I'm not going to lie to you, I don't plan on using any of the commands it says.

I'm not going to touch anything about disabling the "Credentials Manager" or stopping "services" and even less about Credentials and "sfc /scannow chkdsk c: /f /r" is a huge nonsense. It only verifies the integrity of Windows system files,
repairs corrupted or damaged system files,
focuses on critical Windows files.

I'll continue this here: https://github.com/lensapp/lens/issues/8089
