### ISSUE TITLE
View on hover Sidebar doesn't display submenus

### ISSUE THREAD

**Issue by Nokel81** [lensapp/lens#849]
**Describe the bug**
A minimized `class Sidebar` which opens on hover does not display sub menus even when hovering

**To Reproduce**
1. Click on one of the down chevrons to open the namespaces submenu on the sidebar
1. Click the left chevron to minimize the side bar
2. Hover over the side bar
3. When it "opens" observe that the namespaces submenu is both not rendered and that all the chevrons are gone.

**Expected behavior**
The minimizable sidebar should behave like a pinned sidebar when a hover action opens the sidebar.

**Screenshots**
<img width="316" alt="Screen Shot 2020-09-10 at 10 16 40 AM" src="https://user-images.githubusercontent.com/8225332/92743701-c701bd00-f34e-11ea-9296-db244e68237b.png">
<img width="298" alt="Screen Shot 2020-09-10 at 10 16 49 AM" src="https://user-images.githubusercontent.com/8225332/92743708-c832ea00-f34e-11ea-9583-70e6402d889a.png">

**Environment (please complete the following information):**
- Lens Version: 3.6.0-rc2
- OS: [e.g. OSX] macos
- Installation method (e.g. snap or AppImage in Linux): download

**Comment by aleksfront** [comment]
@Nokel81 This is done on purpose because of unclear user experience caused by always-expanded-submenus. Main question was - where to expand submenus: imagine if they're all expanded initially you will see huge unexplainded gaps between an icons. Those gaps would be clear for users only if they hovered over sidebar and wait for second.

If we decide to expand submenus after Sidebar opening animation stops (which itself a tricky task) then your cursor most likely would point to completely different item, not you supposed to click. Just because all menu items expand their children and most icons will jump to another vertical position.

**Comment by Nokel81** [comment]
I can completely understand why expanding them all would be a bad idea (the visual argument is strong).

But I think that there should still be the option to expand them even in the non-pinned mode and I could see an argument for expanding the menu that is currently being hovered over if it was expanded (in pinned mode)
