### ISSUE TITLE
Network Policies Edit Row ordering

### ISSUE THREAD

**Issue by HristoA** [lensapp/lens#98]
**Describe the bug**
When open Network policies for edit and no matter if there is something added or no you click SAVE button ordering of rows is changed (image attached!)

**To Reproduce**
1. Go to 'Netowrk Polices'
2. Click on 'Edit some of existing one'
3. Click `Save`

**Expected behavior**
All the time ordering of rows to be the same!

**Screenshots**
Before clicking `Save`
![image](https://user-images.githubusercontent.com/20325836/69797821-0ce2ff80-11d9-11ea-868b-a25934216aaf.png)
After:
![image](https://user-images.githubusercontent.com/20325836/69797879-208e6600-11d9-11ea-9979-b076e94f4e63.png)

**Environment (please complete the following information):**
- Lens Version: 2.6.4
- OS: Ubuntu 18.0.4
- Installation method (e.g. snap or AppImage in Linux): AppImage

**Comment by jnummelin** [comment]
Looking at the yamls it looks like those are still semantically correct & equivalent, right?

I think this is because after saving the object changes in k8s API and the editor reflects what ever we read from the API. So AFAIK it's actually k8s API that changes the order of keys, which in yamls does not matter.
